name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download env
        uses: subekti404dev/urvault-action@v1
        with:
          secret: ${{ secrets.URVAULT_SECRET }}

      - name: Docker Build
        uses: subekti404dev/docker-build-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: "${{ vars.DOCKER_TAGS }}"
